name: Image CI
# If you update paths, make sure to update them in e2e-test.yml and no-ci.yml as well
on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

permissions:
  contents: read

env:
  artifact_registry: us-central1-docker.pkg.dev
  artifact_repository: polished-enigma-247013/images
  image_name: nginx-debugging-backend

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth-work-identity
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/552057127791/locations/global/workloadIdentityPools/github/providers/github"
          service_account: "container-builder@helical-crowbar-220917.iam.gserviceaccount.com"

      - name: Configure GCloud and Docker
        if: ${{ ! env.ACT }}
        shell: bash
        run: |
          gcloud auth configure-docker
      
      - name: Get version
        id: get-version
        shell: bash
        run: |
          version=$(head -1 version)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: garnercorp/build-actions/image@main
        with:
          container-project: ${{ secrets.PROJECT_ID }}
          image-name: ${{ env.image_name }}
          rc-tag: ${{ steps.get-version.outputs.version }}
          image-tag: ${{ steps.get-version.outputs.version }}
          additional-image-tags: "${{ env.artifact_registry }}/${{ env.artifact_repository }}/${{ env.image_name }}:rc-${{ github.sha }}"
