name: Image CI
# If you update paths, make sure to update them in e2e-test.yml and no-ci.yml as well
on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: "Google Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCR_JSON_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ vars.GCLOUD_SDK_VERSION }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure GCloud and Docker
        if: ${{ ! env.ACT }}
        shell: bash
        run: |
          gcloud auth configure-docker
      
      - name: Get version
        id: get-version
        shell: bash
        run: |
          version=$(head -1 version)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: garnercorp/build-actions/image@main
        with:
          container-project: ${{ secrets.PROJECT_ID }}
          image-name: nginx-debugging-backend
          rc-tag: ${{ steps.get-version.outputs.version }}
          image-tag: ${{ steps.get-version.outputs.version }}
